'use client'
import {useState} from 'react'
import {useAppStore, type BranchData} from '@/lib/store'
import {createClient} from '@/lib/supabase/client'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Card,CardContent} from '@/components/ui/card'
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter} from '@/components/ui/dialog'
import {toast} from 'sonner'
import {MapPin,Plus,Pencil} from 'lucide-react'
const empty={name:'',prefix:'',city:'',address:'',phone:'',email:'',manager_id:'',is_default:false}
export function BranchesClient({initialStaff}:{initialStaff:{id:string;name:string|null;email:string}[]}){
 const {branches,setBranches,activeBranch}=useAppStore()
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<BranchData|null>(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[error,setError]=useState('')
 function show(branch:BranchData|null){setEditing(branch);setForm(branch?{name:branch.name,prefix:branch.prefix,city:branch.city||'',address:branch.address||'',phone:branch.phone||'',email:branch.email||'',manager_id:branch.settings?.manager_id||'',is_default:branch.is_default}:{...empty,is_default:branches.length===0});setError('');setOpen(true)}
 const prefix=form.prefix.toUpperCase().trim()
 const errors={name:form.name.trim().length<2?'Enter at least two characters':'',prefix:!/^[A-Z0-9]{2,8}$/.test(prefix)?'Use 2–8 letters or numbers':branches.some(b=>b.id!==editing?.id&&b.prefix.toUpperCase()===prefix)?'This prefix is already used':'',email:form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)?'Enter a valid email':''}
 async function save(e:React.FormEvent){e.preventDefault();if(Object.values(errors).some(Boolean))return setError('Check the highlighted fields');setSaving(true);setError('');try{const db=createClient();const {data,error}=await (db.rpc as any)('save_branch',{p_id:editing?.id??null,p_input:{...form,prefix}});if(error)throw error;const next=(editing?branches.map(b=>b.id===editing.id?data:b):[...branches,data]).map(b=>data.is_default&&b.id!==data.id?{...b,is_default:false}:b);setBranches(next);setOpen(false);toast.success(editing?'Branch updated':'Branch created')}catch(e){setError(e instanceof Error?e.message:(e as {message?:string}).message||'Could not save branch')}finally{setSaving(false)}}
 const field=(key:'name'|'prefix'|'city'|'address'|'phone'|'email',label:string,placeholder:string)=>{const issue=errors[key as keyof typeof errors];return <label className="grid gap-2 text-sm font-medium">{label}<Input value={form[key]} onChange={e=>setForm(p=>({...p,[key]:key==='prefix'?e.target.value.toUpperCase():e.target.value}))} placeholder={placeholder} type={key==='email'?'email':'text'} aria-invalid={!!error&&!!issue} required={key==='name'||key==='prefix'}/>{error&&issue&&<span className="text-xs text-red-600">{issue}</span>}</label>}
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">Your branches</h2><p className="text-sm text-muted-foreground">{branches.length} locations · Each branch has its own bookings and stock.</p></div><Button onClick={()=>show(null)}><Plus className="mr-2 size-4"/>Add branch</Button></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{branches.map(b=><Card key={b.id}><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-semibold">{b.name}</h3><p className="text-sm text-muted-foreground">{b.prefix} · {b.status}</p></div><Button variant="ghost" size="icon" aria-label={'Edit '+b.name} onClick={()=>show(b)}><Pencil className="size-4"/></Button></div><p className="flex gap-2 text-sm text-muted-foreground"><MapPin className="size-4 shrink-0"/>{[b.address,b.city].filter(Boolean).join(', ')||'Address not added'}</p><div className="flex gap-2 text-xs">{b.is_default&&<span className="rounded-full bg-indigo-50 px-3 py-1 text-indigo-700">Default branch</span>}{b.id===activeBranch?.id&&<span className="rounded-full bg-green-50 px-3 py-1 text-green-700">Current branch</span>}</div></CardContent></Card>)}</div>
 <Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v)}}><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing?'Edit branch':'Register new branch'}</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-6"><fieldset className="space-y-4"><legend className="mb-3 font-semibold">Branch identity</legend>{field('name','Branch name','e.g. Thrissur showroom')}<div className="grid gap-4 sm:grid-cols-2">{field('prefix','Booking prefix','TSR')}{field('city','City','Thrissur')}</div><p className="rounded-xl bg-muted p-3 text-sm">Booking preview: <strong>{prefix||'TSR'}-260916-ABC12345</strong></p></fieldset><fieldset className="space-y-4"><legend className="mb-3 font-semibold">Location and contact</legend>{field('address','Address','Street and building')}<div className="grid gap-4 sm:grid-cols-2">{field('phone','Phone','Contact number')}{field('email','Email','branch@example.com')}</div></fieldset><fieldset className="space-y-4"><legend className="mb-3 font-semibold">Management</legend><label className="grid gap-2 text-sm">Branch manager<select className="h-10 rounded-xl border bg-background px-3" value={form.manager_id} onChange={e=>setForm(p=>({...p,manager_id:e.target.value}))}><option value="">No manager assigned</option>{initialStaff.map(s=><option key={s.id} value={s.id}>{s.name||s.email}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_default} onChange={e=>setForm(p=>({...p,is_default:e.target.checked}))}/>Use as the default branch</label></fieldset>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':'Save branch'}</Button></DialogFooter></form></DialogContent></Dialog></div>
}
